// src/components/SelectorEquipos/SelectorEquipos.tsx
import React, { useEffect, useState } from "react";
import "./SelectorEquipos.css";

interface Team {
  name: string;
  logo: string;
  media: number;
}

interface League {
  id: number;
  nombre: string;
  pais: string;
  categoria: number;
  teams?: Team[];
}

interface Country {
  name: string;
  leagues: League[];
}

type Props = {
  onSelectedTeam: (team: Team) => void;
};

const SelectorEquipos: React.FC<Props> = ({ onSelectedTeam }) => {
  const [countries, setCountries] = useState<Country[]>([]);
  const [selectedCountryIndex, setSelectedCountryIndex] = useState(2);
  const [selectedLeagueIndex, setSelectedLeagueIndex] = useState(0);

  const selectedCountry = countries[selectedCountryIndex];
  const selectedLeague = selectedCountry?.leagues[selectedLeagueIndex];

  const generateLogoPath = (name: string, format: "png" | "webp" = "png") => {
    const basePath = "src/assets/Escudos";
    const fileName = name.replace(/\s+/g, "_").replace(/[()]/g, "");

    if (format === "webp") {
      return `${basePath}/${fileName}.webp`;
    } else {
      return `${basePath}/${fileName}.png`;
    }
  };

const hardcodedCountries: Country[] = [
  {
    name: "Alemania",
    leagues: [
      {
        id: 25,
        nombre: "Bundesliga",
        pais: "Alemania",
        categoria: 1,
        teams: [
          { name: "Bayern Munich", logo: generateLogoPath("Bayern Munich"), media: 89 },
          { name: "Borussia Dortmund", logo: generateLogoPath("Borussia Dortmund"), media: 84 },
          { name: "RB Leipzig", logo: generateLogoPath("RB Leipzig"), media: 83 },
          { name: "Bayer Leverkusen", logo: generateLogoPath("Bayer Leverkusen"), media: 85 },
          { name: "Union Berlin", logo: generateLogoPath("Union Berlin"), media: 79 },
          { name: "Eintracht Frankfurt", logo: generateLogoPath("Eintracht Frankfurt"), media: 80 },
          { name: "Freiburg", logo: generateLogoPath("Freiburg"), media: 78 },
          { name: "Wolfsburg", logo: generateLogoPath("Wolfsburg"), media: 77 },
          { name: "Borussia M'Gladbach", logo: generateLogoPath("Borussia M'Gladbach"), media: 76 },
          { name: "Mainz 05", logo: generateLogoPath("Mainz 05"), media: 75 },
          { name: "Köln", logo: generateLogoPath("Köln"), media: 74 },
          { name: "Augsburg", logo: generateLogoPath("Augsburg"), media: 73 },
          { name: "Stuttgart", logo: generateLogoPath("Stuttgart"), media: 79 },
          { name: "Werder Bremen", logo: generateLogoPath("Werder Bremen"), media: 74 },
          { name: "Hertha Berlin", logo: generateLogoPath("Hertha Berlin"), media: 72 },
          { name: "Hamburger", logo: generateLogoPath("Hamburger"), media: 70 },
          { name: "Schalke 04", logo: generateLogoPath("Schalke 04"), media: 69 },
          { name: "Hoffenheim", logo: generateLogoPath("Hoffenheim"), media: 75 },
        ],
      },
      {
        id: 29,
        nombre: "2. Bundesliga",
        pais: "Alemania",
        categoria: 2,
        teams: [
        ],
      },
    ],
  },
  {
    name: "Arabia Saudita",
    leagues: [
      {
        id: 16,
        nombre: "Saudi Pro League",
        pais: "Arabia Saudita",
        categoria: 1,
        teams: [
          { name: "Al-Hilal", logo: generateLogoPath("Al-Hilal"), media: 81 },
          { name: "Al-Ittihad", logo: generateLogoPath("Al-Ittihad"), media: 79 },
          { name: "Al-Nassr", logo: generateLogoPath("Al-Nassr"), media: 80 },
          { name: "Al-Ahli", logo: generateLogoPath("Al-Ahli"), media: 75 },
          { name: "Al-Qadsiah", logo: generateLogoPath("Al-Qadsiah"), media: 76 },
          { name: "Neom SC", logo: generateLogoPath("Neom SC"), media: 73 },
          { name: "Al-Taawoun", logo: generateLogoPath("Al-Taawoun"), media: 72 },
          { name: "Al-Khaleej", logo: generateLogoPath("Al-Khaleej"), media: 70 },
          { name: "Al-Ettifaq", logo: generateLogoPath("Al-Ettifaq"), media: 69 },
          { name: "Al-Shabab", logo: generateLogoPath("Al-Shabab"), media: 69 },
          { name: "Al-Fateh", logo: generateLogoPath("Al-Fateh"), media: 67 },
          { name: "Al-Fayha", logo: generateLogoPath("Al-Fayha"), media: 70 },
          { name: "Al-Riyadh", logo: generateLogoPath("Al-Riyadh"), media: 65 },
          { name: "Al-Okhdood", logo: generateLogoPath("Al-Okhdood"), media: 67 },
          { name: "Damac", logo: generateLogoPath("Damac"), media: 63 },
          { name: "Al-Hazem", logo: generateLogoPath("Al-Hazem"), media: 61 },
          { name: "Al-Najma", logo: generateLogoPath("Al-Najma"), media: 64 },
          { name: "Al-Kholood", logo: generateLogoPath("Al-Kholood"), media: 65 },
        ],
      },
    ],
  },
  {
    name: "Argentina",
    leagues: [
      {
        id: 1,
        nombre: "Primera División",
        pais: "Argentina",
        categoria: 1,
        teams: [
          { name: "Aldosivi", logo: generateLogoPath("Aldosivi"), media: 66 },
          { name: "Argentinos Juniors", logo: generateLogoPath("Argentinos Juniors"), media: 73 },
          { name: "Atlético Tucumán", logo: generateLogoPath("Atlético Tucumán"), media: 68 },
          { name: "Banfield", logo: generateLogoPath("Banfield"), media: 71 },
          { name: "Barracas Central", logo: generateLogoPath("Barracas Central"), media: 61 },
          { name: "Belgrano", logo: generateLogoPath("Belgrano"), media: 70 },
          { name: "Boca Juniors", logo: generateLogoPath("Boca Juniors"), media: 80 },
          { name: "Central Córdoba (SdE)", logo: generateLogoPath("Central Córdoba (SdE)"), media: 69 },
          { name: "Defensa y Justicia", logo: generateLogoPath("Defensa y Justicia"), media: 73 },
          { name: "Deportivo Riestra", logo: generateLogoPath("Deportivo Riestra"), media: 61 },
          { name: "Estudiantes (LP)", logo: generateLogoPath("Estudiantes (LP)"), media: 77 },
          { name: "Estudiantes (Río Cuarto)", logo: generateLogoPath("Estudiantes (Río Cuarto)"), media: 64 },
          { name: "Gimnasia (LP)", logo: generateLogoPath("Gimnasia (LP)"), media: 70 },
          { name: "Gimnasia (Mza)", logo: generateLogoPath("Gimnasia (Mza)"), media: 66 },
          { name: "Huracán", logo: generateLogoPath("Huracán"), media: 73 },
          { name: "Independiente", logo: generateLogoPath("Independiente"), media: 76 },
          { name: "Independiente Rivadavia", logo: generateLogoPath("Independiente Rivadavia"), media: 66 },
          { name: "Instituto", logo: generateLogoPath("Instituto"), media: 68 },
          { name: "Lanús", logo: generateLogoPath("Lanús"), media: 76 },
          { name: "Newell's", logo: generateLogoPath("Newell's"), media: 73 },
          { name: "Platense", logo: generateLogoPath("Platense"), media: 70 },
          { name: "Racing Club", logo: generateLogoPath("Racing Club"), media: 78 },
          { name: "River Plate", logo: generateLogoPath("River Plate"), media: 81 },
          { name: "Rosario Central", logo: generateLogoPath("Rosario Central"), media: 72 },
          { name: "San Lorenzo", logo: generateLogoPath("San Lorenzo"), media: 77 },
          { name: "Sarmiento (J)", logo: generateLogoPath("Sarmiento (J)"), media: 68 },
          { name: "Talleres (C)", logo: generateLogoPath("Talleres (C)"), media: 76 },
          { name: "Tigre", logo: generateLogoPath("Tigre"), media: 69 },
          { name: "Unión", logo: generateLogoPath("Unión"), media: 69 },
          { name: "Vélez Sarsfield", logo: generateLogoPath("Vélez Sarsfield"), media: 74 },
        ],
      },
      {
        id: 13,
        nombre: "B Nacional",
        pais: "Argentina",
        categoria: 2,
        teams: [
          { name: "Acassuso", logo: generateLogoPath("Acassuso"), media: 56 },
          { name: "Agropecuario", logo: generateLogoPath("Agropecuario"), media: 67 },
          { name: "Almagro", logo: generateLogoPath("Almagro"), media: 63 },
          { name: "All Boys", logo: generateLogoPath("All Boys"), media: 65 },
          { name: "Almirante Brown", logo: generateLogoPath("Almirante Brown"), media: 66 },
          { name: "Atlanta", logo: generateLogoPath("Atlanta"), media: 64 },
          { name: "Atlético de Rafaela", logo: generateLogoPath("Atlético de Rafaela"), media: 68 },
          { name: "Central Norte", logo: generateLogoPath("Central Norte"), media: 59 },
          { name: "Chacarita", logo: generateLogoPath("Chacarita"), media: 69 },
          { name: "Chaco For Ever", logo: generateLogoPath("Chaco For Ever"), media: 62 },
          { name: "Ciudad Bolívar", logo: generateLogoPath("Ciudad Bolívar"), media: 50 },
          { name: "Colegiales", logo: generateLogoPath("Colegiales"), media: 61 },
          { name: "Colón", logo: generateLogoPath("Colón"), media: 69 },
          { name: "Defensores de Belgrano", logo: generateLogoPath("Defensores de Belgrano"), media: 67 },
          { name: "Deportivo Madryn", logo: generateLogoPath("Deportivo Madryn"), media: 62 },
          { name: "Deportivo Maipú", logo: generateLogoPath("Deportivo Maipú"), media: 66 },
          { name: "Deportivo Morón", logo: generateLogoPath("Deportivo Morón"), media: 63 },
          { name: "Estudiantes (Bs As)", logo: generateLogoPath("Estudiantes (Bs As)"), media: 66 },
          { name: "Ferro", logo: generateLogoPath("Ferro"), media: 68 },
          { name: "Gimnasia de Jujuy", logo: generateLogoPath("Gimnasia de Jujuy"), media: 66 },
          { name: "Gimnasia y Tiro", logo: generateLogoPath("Gimnasia y Tiro"), media: 1 },
          { name: "Godoy Cruz", logo: generateLogoPath("Godoy Cruz"), media: 72 },
          { name: "Güemes", logo: generateLogoPath("Güemes"), media: 62 },
          { name: "Los Andes", logo: generateLogoPath("Los Andes"), media: 58 },
          { name: "Mitre (SdE)", logo: generateLogoPath("Mitre (SdE)"), media: 65 },
          { name: "Nueva Chicago", logo: generateLogoPath("Nueva Chicago"), media: 63 },
          { name: "Patronato", logo: generateLogoPath("Patronato"), media: 70 },
          { name: "Quilmes", logo: generateLogoPath("Quilmes"), media: 69 },
          { name: "Racing (Córdoba)", logo: generateLogoPath("Racing (Córdoba)"), media: 61 },
          { name: "San Martín (SJ)", logo: generateLogoPath("San Martín (SJ)"), media: 65 },
          { name: "San Martín (T)", logo: generateLogoPath("San Martín (T)"), media: 67 },
          { name: "San Miguel", logo: generateLogoPath("San Miguel"), media: 50 },
          { name: "San Telmo", logo: generateLogoPath("San Telmo"), media: 64 },
          { name: "Temperley", logo: generateLogoPath("Temperley"), media: 67 },
          { name: "Tristán Suárez", logo: generateLogoPath("Tristán Suárez"), media: 61 },
          { name: "Midland", logo: generateLogoPath("Midland"), media: 54 },
        ],
      },
      {
        id: 14,
        nombre: "B Metropolitana",
        pais: "Argentina",
        categoria: 4,
        teams: [
          { name: "Arsenal", logo: generateLogoPath("Arsenal"), media: 1 },
          { name: "Argentino de Merlo", logo: generateLogoPath("Argentino de Merlo"), media: 53 },
          { name: "Argentino de Quilmes", logo: generateLogoPath("Argentino de Quilmes"), media: 53 },
          { name: "Brown (Adrogué)", logo: generateLogoPath("Brown (Adrogué)"), media: 64 },
          { name: "Comunicaciones", logo: generateLogoPath("Comunicaciones"), media: 59 },
          { name: "Defensores Unidos", logo: generateLogoPath("Defensores Unidos"), media: 61 },
          { name: "Deportivo Armenio", logo: generateLogoPath("Deportivo Armenio"), media: 56 },
          { name: "Deportivo Camioneros", logo: generateLogoPath("Deportivo Camioneros"), media: 1 },
          { name: "Laferrere", logo: generateLogoPath("Laferrere"), media: 54 },
          { name: "Deportivo Merlo", logo: generateLogoPath("Deportivo Merlo"), media: 55 },
          { name: "Dock Sud", logo: generateLogoPath("Dock Sud"), media: 52 },
          { name: "Excursionistas", logo: generateLogoPath("Excursionistas"), media: 54 },
          { name: "Flandria", logo: generateLogoPath("Flandria"), media: 63 },
          { name: "Ituzaingó", logo: generateLogoPath("Ituzaingó"), media: 57 },
          { name: "Liniers", logo: generateLogoPath("Liniers"), media: 54 },
          { name: "Real Pilar", logo: generateLogoPath("Real Pilar"), media: 53 },
          { name: "San Martín Burzaco", logo: generateLogoPath("San Martín Burzaco"), media: 53 },
          { name: "Sportivo Italiano", logo: generateLogoPath("Sportivo Italiano"), media: 51 },
          { name: "Talleres (RdE)", logo: generateLogoPath("Talleres (RdE)"), media: 53 },
          { name: "UAI Urquiza", logo: generateLogoPath("UAI Urquiza"), media: 58 },
          { name: "Villa Dálmine", logo: generateLogoPath("Villa Dálmine"), media: 64 },
          { name: "Villa San Carlos", logo: generateLogoPath("Villa San Carlos"), media: 52 },
        ],
      },
      {
        id: 44,
        nombre: "Primera C",
        pais: "Argentina",
        categoria: 5,
        teams: [
          { name: "Argentino (Rosario)", logo: generateLogoPath("Argentino (Rosario)"), media: 1 },
          { name: "Atlas", logo: generateLogoPath("Atlas"), media: 52 },
          { name: "Berazategui", logo: generateLogoPath("Berazategui"), media: 51 },
          { name: "Cañuelas", logo: generateLogoPath("Cañuelas"), media: 50 },
          { name: "Central Ballester", logo: generateLogoPath("Central Ballester"), media: 47 },
          { name: "Central Córdoba (R)", logo: generateLogoPath("Central Córdoba (R)"), media: 51 },
          { name: "Centro Español", logo: generateLogoPath("Centro Español"), media: 52 },
          { name: "Claypole", logo: generateLogoPath("Claypole"), media: 50 },
          { name: "Cambaceres", logo: generateLogoPath("Cambaceres"), media: 51 },
          { name: "Deportivo Español", logo: generateLogoPath("Deportivo Español"), media: 53 },
          { name: "Deportivo Paraguayo", logo: generateLogoPath("Deportivo Paraguayo"), media: 46 },
          { name: "El Porvenir", logo: generateLogoPath("El Porvenir"), media: 49 },
          { name: "Estrella del Sur", logo: generateLogoPath("Estrella del Sur"), media: 1 },
          { name: "Fénix", logo: generateLogoPath("Fénix"), media: 53 },
          { name: "General Lamadrid", logo: generateLogoPath("General Lamadrid"), media: 52 },
          { name: "J.J. Urquiza", logo: generateLogoPath("J.J. Urquiza"), media: 55 },
          { name: "Juventud Unida", logo: generateLogoPath("Juventud Unida"), media: 51 },
          { name: "Leones FC", logo: generateLogoPath("Leones FC"), media: 1 },
          { name: "Leandro N. Alem", logo: generateLogoPath("Leandro N. Alem"), media: 52 },
          { name: "Lugano", logo: generateLogoPath("Lugano"), media: 51 },
          { name: "Luján", logo: generateLogoPath("Luján"), media: 52 },
          { name: "Mercedes", logo: generateLogoPath("Mercedes"), media: 1 },
          { name: "Muñiz", logo: generateLogoPath("Muñiz"), media: 51 },
          { name: "Puerto Nuevo", logo: generateLogoPath("Puerto Nuevo"), media: 48 },
          { name: "Sacachispas", logo: generateLogoPath("Sacachispas"), media: 60 },
          { name: "Sportivo Barracas", logo: generateLogoPath("Sportivo Barracas"), media: 49 },
          { name: "Victoriano Arenas", logo: generateLogoPath("Victoriano Arenas"), media: 52 },
          { name: "Yupanqui", logo: generateLogoPath("Yupanqui"), media: 49 },
        ],
      },
      {
        id: 15,
        nombre: "Federal A",
        pais: "Argentina",
        categoria: 4,
        teams: [
          { name: "9 de Julio", logo: generateLogoPath("9 de Julio"), media: 47 },
          { name: "Alvarado", logo: generateLogoPath("Alvarado"), media: 63 },
          { name: "Atenas", logo: generateLogoPath("Atenas"), media: 1 },
          { name: "Bartolomé Mitre", logo: generateLogoPath("Bartolomé Mitre"), media: 1 },
          { name: "Boca Unidos", logo: generateLogoPath("Boca Unidos"), media: 56 },
          { name: "Círculo Dep. Otamendi", logo: generateLogoPath("Círculo Dep. Otamendi"), media: 53 },
          { name: "Cipolletti", logo: generateLogoPath("Cipolletti"), media: 60 },
          { name: "Costa Brava", logo: generateLogoPath("Costa Brava"), media: 1 },
          { name: "Defensores de Belgrano (Villa Ramallo)", logo: generateLogoPath("Defensores de Belgrano (Villa Ramallo)"), media: 1 },
          { name: "Defensores de Puerto Vilelas", logo: generateLogoPath("Defensores de Puerto Vilelas"), media: 1 },
          { name: "Deportivo Argentino", logo: generateLogoPath("Deportivo Argentino"), media: 1 },
          { name: "Deportivo Rincón", logo: generateLogoPath("Deportivo Rincón"), media: 1 },
          { name: "Douglas Haig", logo: generateLogoPath("Douglas Haig"), media: 62 },
          { name: "El Linqueño", logo: generateLogoPath("El Linqueño"), media: 53 },
          { name: "Escobar FC", logo: generateLogoPath("Escobar FC"), media: 1 },
          { name: "FADEP", logo: generateLogoPath("FADEP"), media: 1 },
          { name: "Germinal", logo: generateLogoPath("Germinal"), media: 52 },
          { name: "Gimnasia y Esgrima de Chivilcoy", logo: generateLogoPath("Gimnasia y Esgrima de Chivilcoy"), media: 1 },
          { name: "Gimnasia (CDU)", logo: generateLogoPath("Gimnasia (CDU)"), media: 60 },
          { name: "Gmo. Brown (Madryn)", logo: generateLogoPath("Gmo. Brown (Madryn)"), media: 64 },
          { name: "Huracán Las Heras", logo: generateLogoPath("Huracán Las Heras"), media: 51 },
          { name: "Independiente", logo: generateLogoPath("Independiente"), media: 76 },
          { name: "Juventud Antoniana", logo: generateLogoPath("Juventud Antoniana"), media: 58 },
          { name: "Juventud Unida Universitario", logo: generateLogoPath("Juventud Unida Universitario"), media: 1 },
          { name: "Kimberley", logo: generateLogoPath("Kimberley"), media: 46 },
          { name: "Olimpo", logo: generateLogoPath("Olimpo"), media: 62 },
          { name: "San Martín", logo: generateLogoPath("San Martín"), media: 1 },
          { name: "San Martín (Mza)", logo: generateLogoPath("San Martín (Mza)"), media: 51 },
          { name: "Santamarina", logo: generateLogoPath("Santamarina"), media: 61 },
          { name: "Sarmiento (La Banda)", logo: generateLogoPath("Sarmiento (La Banda)"), media: 1 },
          { name: "Sarmiento (Resistencia)", logo: generateLogoPath("Sarmiento (Resistencia)"), media: 1 },
          { name: "Sol de América (F)", logo: generateLogoPath("Sol de América (F)"), media: 52 },
          { name: "Sol de Mayo", logo: generateLogoPath("Sol de Mayo"), media: 60 },
          { name: "Sportivo AC", logo: generateLogoPath("Sportivo AC"), media: 1 },
          { name: "Sportivo Belgrano", logo: generateLogoPath("Sportivo Belgrano"), media: 59 },
          { name: "Tucumán Central", logo: generateLogoPath("Tucumán Central"), media: 1 },
          { name: "Villa Mitre", logo: generateLogoPath("Villa Mitre"), media: 56 },
        ],
      },
    ],
  },
    {
    name: "Brasil",
    leagues: [
      {
        id: 6,
        nombre: "Série A",
        pais: "Brasil",
        categoria: 1,
        teams: [
          { name: "Flamengo", logo: generateLogoPath("Flamengo"), media: 83 },
          { name: "América MG", logo: generateLogoPath("América MG"), media: 70 },
          { name: "Athl. Paranaense", logo: generateLogoPath("Athl. Paranaense"), media: 78 },
          { name: "Atlético Mineiro", logo: generateLogoPath("Atlético Mineiro"), media: 81 },
          { name: "Botafogo", logo: generateLogoPath("Botafogo"), media: 77 },
          { name: "Ceará", logo: generateLogoPath("Ceará"), media: 72 },
          { name: "Corinthians", logo: generateLogoPath("Corinthians"), media: 76 },
          { name: "Coritiba", logo: generateLogoPath("Coritiba"), media: 70 },
          { name: "Cruzeiro", logo: generateLogoPath("Cruzeiro"), media: 71 },
          { name: "Cuiabá", logo: generateLogoPath("Cuiabá"), media: 67 },
          { name: "Fluminense", logo: generateLogoPath("Fluminense"), media: 80 },
          { name: "Fortaleza", logo: generateLogoPath("Fortaleza"), media: 75 },
          { name: "Goias", logo: generateLogoPath("Goias"), media: 72 },
          { name: "Gremio", logo: generateLogoPath("Gremio"), media: 74 },
          { name: "Internacional", logo: generateLogoPath("Internacional"), media: 77 },
          { name: "Palmeiras", logo: generateLogoPath("Palmeiras"), media: 82 },
          { name: "RB Bragantino", logo: generateLogoPath("RB Bragantino"), media: 77 },
          { name: "Santos", logo: generateLogoPath("Santos"), media: 73 },
          { name: "Sao Paulo", logo: generateLogoPath("Sao Paulo"), media: 76 },
          { name: "Vasco da Gama", logo: generateLogoPath("Vasco da Gama"), media: 70 },
        ],
      },
    ],
  },
  {
    name: "Colombia",
    leagues: [
      {
        id: 18,
        nombre: "Primera A",
        pais: "Colombia",
        categoria: 1,
        teams: [
          { name: "Independiente Medellín", logo: generateLogoPath("Independiente Medellín"), media: 69 },
          { name: "Deportes Tolima", logo: generateLogoPath("Deportes Tolima"), media: 69 },
          { name: "Atlético Nacional", logo: generateLogoPath("Atlético Nacional"), media: 74 },
          { name: "Atlético Bucaramanga", logo: generateLogoPath("Atlético Bucaramanga"), media: 69 },
          { name: "Junior", logo: generateLogoPath("Junior"), media: 70 },
          { name: "Fortaleza", logo: generateLogoPath("Fortaleza"), media: 67 },
          { name: "Independiente Santa Fe", logo: generateLogoPath("Independiente Santa Fe"), media: 68 },
          { name: "América de Cali", logo: generateLogoPath("América de Cali"), media: 68 },
          { name: "Alianza Valledupar", logo: generateLogoPath("Alianza Valledupar"), media: 66 },
          { name: "Águilas Doradas", logo: generateLogoPath("Águilas Doradas"), media: 65 },
          { name: "Once Caldas", logo: generateLogoPath("Once Caldas"), media: 69 },
          { name: "Millonarios", logo: generateLogoPath("Millonarios"), media: 68 },
          { name: "Llaneros", logo: generateLogoPath("Llaneros"), media: 66 },
          { name: "Deportivo Cali", logo: generateLogoPath("Deportivo Cali"), media: 67 },
          { name: "Unión Magdalena", logo: generateLogoPath("Unión Magdalena"), media: 64 },
          { name: "Envigado", logo: generateLogoPath("Envigado"), media: 65 },
          { name: "Deportivo Pasto", logo: generateLogoPath("Deportivo Pasto"), media: 63 },
          { name: "Deportivo Pereira", logo: generateLogoPath("Deportivo Pereira"), media: 64 },
          { name: "Boyacá Chicó", logo: generateLogoPath("Boyacá Chicó"), media: 61 },
          { name: "La Equidad", logo: generateLogoPath("La Equidad"), media: 62 },
        ],
      },
    ],
  },
  {
    name: "España",
    leagues: [
      {
        id: 4,
        nombre: "La Liga",
        pais: "España",
        categoria: 1,
        teams: [
          { name: "Real Madrid", logo: generateLogoPath("Real Madrid"), media: 90 },
          { name: "Barcelona", logo: generateLogoPath("Barcelona"), media: 89 },
          { name: "Atlético Madrid", logo: generateLogoPath("Atlético Madrid"), media: 84 },
          { name: "Sevilla", logo: generateLogoPath("Sevilla"), media: 80 },
          { name: "Real Sociedad", logo: generateLogoPath("Real Sociedad"), media: 82 },
          { name: "Athletic Club", logo: generateLogoPath("Athletic Club"), media: 80 },
          { name: "Villarreal", logo: generateLogoPath("Villarreal"), media: 81 },
          { name: "Real Betis", logo: generateLogoPath("Real Betis"), media: 80 },
          { name: "Getafe", logo: generateLogoPath("Getafe"), media: 75 },
          { name: "Rayo Vallecano", logo: generateLogoPath("Rayo Vallecano"), media: 74 },
          { name: "Valencia", logo: generateLogoPath("Valencia"), media: 76 },
          { name: "Granada", logo: generateLogoPath("Granada"), media: 70 },
          { name: "Alavés", logo: generateLogoPath("Alavés"), media: 72 },
          { name: "Espanyol", logo: generateLogoPath("Espanyol"), media: 70 },
          { name: "Almería", logo: generateLogoPath("Almería"), media: 69 },
          { name: "Girona", logo: generateLogoPath("Girona"), media: 76 },
          { name: "Real Valladolid", logo: generateLogoPath("Real Valladolid"), media: 71 },
          { name: "Sporting Gijón", logo: generateLogoPath("Sporting Gijón"), media: 70 },
          { name: "Elche", logo: generateLogoPath("Elche"), media: 72 },
          { name: "Real Murcia", logo: generateLogoPath("Real Murcia"), media: 65 },
        ],
      },
      {
        id: 31,
        nombre: "Segunda División",
        pais: "España",
        categoria: 2,
        teams: [
          { name: "Celta de Vigo", logo: generateLogoPath("Celta de Vigo"), media: 75 },
          { name: "Osasuna", logo: generateLogoPath("Osasuna"), media: 74 },
          { name: "Mallorca", logo: generateLogoPath("Mallorca"), media: 73 },
          { name: "Las Palmas", logo: generateLogoPath("Las Palmas"), media: 71 },
          { name: "FC Andorra", logo: generateLogoPath("FC Andorra"), media: 64 },
          { name: "Eibar", logo: generateLogoPath("Eibar"), media: 66 },
          { name: "Racing Santander", logo: generateLogoPath("Racing Santander"), media: 73 },
          { name: "Racing de Ferrol", logo: generateLogoPath("Racing de Ferrol"), media: 61 },
          { name: "Málaga", logo: generateLogoPath("Málaga"), media: 67 },
          { name: "Levante", logo: generateLogoPath("Levante"), media: 72 },
          { name: "Burgos", logo: generateLogoPath("Burgos"), media: 68 },
          { name: "Tenerife", logo: generateLogoPath("Tenerife"), media: 62 },
          { name: "Albacete", logo: generateLogoPath("Albacete"), media: 65 },
          { name: "Real Oviedo", logo: generateLogoPath("Real Oviedo"), media: 72 },
          { name: "Córdoba", logo: generateLogoPath("Córdoba"), media: 64 },
          { name: "Cádiz", logo: generateLogoPath("Cádiz"), media: 69 },
          { name: "Castellón", logo: generateLogoPath("Castellón"), media: 68 },
          { name: "Huesca", logo: generateLogoPath("Huesca"), media: 63 },
          { name: "Cultural Leonesa", logo: generateLogoPath("Cultural Leonesa"), media: 64 },
          { name: "Leganés", logo: generateLogoPath("Leganés"), media: 65 },
          { name: "Deportivo La Coruña", logo: generateLogoPath("Deportivo La Coruña"), media: 70 },
          { name: "Real Zaragoza", logo: generateLogoPath("Real Zaragoza"), media: 61 },
        ],
      },
      {
        id: 51,
        nombre: "Primera Federación",
        pais: "España",
        categoria: 3,
        teams: [
          { name: "Mirandés", logo: generateLogoPath("Mirandés"), media: 61 },
          { name: "Ceuta", logo: generateLogoPath("Ceuta"), media: 64 },
          { name: "Eldense", logo: generateLogoPath("Eldense"), media: 60 },
          { name: "Alcorcón", logo: generateLogoPath("Alcorcón"), media: 57 },
          { name: "Alcoyano", logo: generateLogoPath("Alcoyano"), media: 62 },
          { name: "Fuenlabrada", logo: generateLogoPath("Fuenlabrada"), media: 61 },
          { name: "Unionistas de Salamanca", logo: generateLogoPath("Unionistas de Salamanca"), media: 64 },
          { name: "Amorebieta", logo: generateLogoPath("Amorebieta"), media: 55 },
          { name: "Ibiza", logo: generateLogoPath("Ibiza"), media: 53 },
          { name: "Recreativo", logo: generateLogoPath("Recreativo"), media: 59 },
          { name: "Badajoz", logo: generateLogoPath("Badajoz"), media: 57 },
          { name: "Cartagena", logo: generateLogoPath("Cartagena"), media: 65 },
          { name: "Gimnástic", logo: generateLogoPath("Gimnástic"), media: 62 },
          { name: "Lugo", logo: generateLogoPath("Lugo"), media: 53 },
          { name: "Numancia", logo: generateLogoPath("Numancia"), media: 62 },
          { name: "Zamora", logo: generateLogoPath("Zamora"), media: 60 },
          { name: "Mérida", logo: generateLogoPath("Mérida"), media: 57 },
          { name: "Barakaldo", logo: generateLogoPath("Barakaldo"), media: 55 },
          { name: "Hércules", logo: generateLogoPath("Hércules"), media: 58 },
          { name: "Ponferradina", logo: generateLogoPath("Ponferradina"), media: 58 },
          { name: "Sabadell", logo: generateLogoPath("Sabadell"), media: 54 },
          { name: "Pontevedra", logo: generateLogoPath("Pontevedra"), media: 63 },
        ],
      },
    ],
  },
  {
    name: "Estados Unidos",
    leagues: [
      {
        id: 7,
        nombre: "MLS",
        pais: "Estados Unidos",
        categoria: 1,
        teams: [
          { name: "CF Montreal", logo: generateLogoPath("CF Montreal"), media: 72 },
          { name: "Inter Miami", logo: generateLogoPath("Inter Miami"), media: 80 },
          { name: "Los Angeles FC", logo: generateLogoPath("Los Angeles FC"), media: 78 },
          { name: "New England Revolution", logo: generateLogoPath("New England Revolution"), media: 72 },
          { name: "New York City", logo: generateLogoPath("New York City"), media: 74 },
          { name: "Philadelphia Union", logo: generateLogoPath("Philadelphia Union"), media: 72 },
          { name: "Seattle Sounders", logo: generateLogoPath("Seattle Sounders"), media: 75 },
          { name: "Atlanta United", logo: generateLogoPath("Atlanta United"), media: 76 },
          { name: "Austin FC", logo: generateLogoPath("Austin FC"), media: 72 },
          { name: "Charlotte FC", logo: generateLogoPath("Charlotte FC"), media: 70 },
          { name: "Chicago Fire", logo: generateLogoPath("Chicago Fire"), media: 68 },
          { name: "FC Cincinnati", logo: generateLogoPath("FC Cincinnati"), media: 74 },
          { name: "Colorado Rapids", logo: generateLogoPath("Colorado Rapids"), media: 68 },
          { name: "Columbus Crew", logo: generateLogoPath("Columbus Crew"), media: 73 },
          { name: "DC United", logo: generateLogoPath("DC United"), media: 67 },
          { name: "FC Dallas", logo: generateLogoPath("FC Dallas"), media: 70 },
          { name: "Houston Dynamo", logo: generateLogoPath("Houston Dynamo"), media: 69 },
          { name: "Los Angeles Galaxy", logo: generateLogoPath("Los Angeles Galaxy"), media: 75 },
          { name: "Minnesota United", logo: generateLogoPath("Minnesota United"), media: 71 },
          { name: "Nashville SC", logo: generateLogoPath("Nashville SC"), media: 69 },
          { name: "Orlando City", logo: generateLogoPath("Orlando City"), media: 72 },
          { name: "Portland Timbers", logo: generateLogoPath("Portland Timbers"), media: 73 },
          { name: "Real Salt Lake", logo: generateLogoPath("Real Salt Lake"), media: 70 },
          { name: "San Diego FC", logo: generateLogoPath("San Diego FC"), media: 68 },
          { name: "San Jose Earthquakes", logo: generateLogoPath("San Jose Earthquakes"), media: 67 },
          { name: "Sporting Kansas City", logo: generateLogoPath("Sporting Kansas City"), media: 71 },
          { name: "St. Louis City", logo: generateLogoPath("St. Louis City"), media: 69 },
          { name: "Toronto FC", logo: generateLogoPath("Toronto FC"), media: 68 },
          { name: "Vancouver Whitecaps", logo: generateLogoPath("Vancouver Whitecaps"), media: 68 },
          { name: "New York Red Bulls", logo: generateLogoPath("New York Red Bulls"), media: 75 },
        ],
      },
    ],
  },
  {
    name: "Francia",
    leagues: [
      {
        id: 3,
        nombre: "Ligue 1",
        pais: "Francia",
        categoria: 1,
        teams: [
          { name: "Ajaccio", logo: generateLogoPath("Ajaccio"), media: 73 },
          { name: "Angers", logo: generateLogoPath("Angers"), media: 72 },
          { name: "AS Monaco", logo: generateLogoPath("AS Monaco"), media: 80 },
          { name: "Auxerre", logo: generateLogoPath("Auxerre"), media: 73 },
          { name: "Brest", logo: generateLogoPath("Brest"), media: 73 },
          { name: "Paris FC", logo: generateLogoPath("Paris FC"), media: 73 },
          { name: "Lens", logo: generateLogoPath("Lens"), media: 79 },
          { name: "Lille", logo: generateLogoPath("Lille"), media: 78 },
          { name: "Lorient", logo: generateLogoPath("Lorient"), media: 75 },
          { name: "Lyon", logo: generateLogoPath("Lyon"), media: 80 },
          { name: "Montpellier", logo: generateLogoPath("Montpellier"), media: 75 },
          { name: "Nantes", logo: generateLogoPath("Nantes"), media: 75 },
          { name: "Nice", logo: generateLogoPath("Nice"), media: 77 },
          { name: "Olympique Marseille", logo: generateLogoPath("Olympique Marseille"), media: 81 },
          { name: "Paris Saint-Germain", logo: generateLogoPath("Paris Saint-Germain"), media: 87 },
          { name: "Racing Strasbourg", logo: generateLogoPath("Racing Strasbourg"), media: 74 },
          { name: "Rennes", logo: generateLogoPath("Rennes"), media: 78 },
          { name: "Stade de Reims", logo: generateLogoPath("Stade de Reims"), media: 75 },
          { name: "Toulouse", logo: generateLogoPath("Toulouse"), media: 76 },
          { name: "Troyes", logo: generateLogoPath("Troyes"), media: 74 },
        ],
      },
      {
        id: 30,
        nombre: "Ligue 2",
        pais: "Francia",
        categoria: 2,
        teams: [
        ],
      },
    ],
  },
  {
    name: "Inglaterra",
    leagues: [
      {
        id: 2,
        nombre: "Premier League",
        pais: "Inglaterra",
        categoria: 1,
        teams: [
          { name: "Manchester City", logo: generateLogoPath("Manchester City"), media: 87 },
          { name: "Liverpool", logo: generateLogoPath("Liverpool"), media: 87 },
          { name: "Arsenal", logo: generateLogoPath("Arsenal"), media: 86 },
          { name: "Manchester United", logo: generateLogoPath("Manchester United"), media: 82 },
          { name: "Chelsea", logo: generateLogoPath("Chelsea"), media: 81 },
          { name: "Tottenham Hotspur", logo: generateLogoPath("Tottenham Hotspur"), media: 83 },
          { name: "Newcastle United", logo: generateLogoPath("Newcastle United"), media: 80 },
          { name: "Aston Villa", logo: generateLogoPath("Aston Villa"), media: 79 },
          { name: "West Ham United", logo: generateLogoPath("West Ham United"), media: 78 },
          { name: "Brighton", logo: generateLogoPath("Brighton"), media: 78 },
          { name: "Crystal Palace", logo: generateLogoPath("Crystal Palace"), media: 76 },
          { name: "Fulham", logo: generateLogoPath("Fulham"), media: 75 },
          { name: "Wolverhampton", logo: generateLogoPath("Wolverhampton"), media: 74 },
          { name: "Everton", logo: generateLogoPath("Everton"), media: 73 },
          { name: "Bournemouth", logo: generateLogoPath("Bournemouth"), media: 73 },
          { name: "Sheffield United", logo: generateLogoPath("Sheffield United"), media: 68 },
          { name: "Cardiff City", logo: generateLogoPath("Cardiff City"), media: 71 },
          { name: "Leicester City", logo: generateLogoPath("Leicester City"), media: 75 },
          { name: "Watford", logo: generateLogoPath("Watford"), media: 72 },
          { name: "West Bromwich", logo: generateLogoPath("West Bromwich"), media: 71 },
        ],
      },
      {
        id: 27,
        nombre: "Championship",
        pais: "Inglaterra",
        categoria: 2,
        teams: [
          { name: "Brentford", logo: generateLogoPath("Brentford"), media: 75 },
          { name: "Nottingham Forest", logo: generateLogoPath("Nottingham Forest"), media: 73 },
          { name: "Burnley", logo: generateLogoPath("Burnley"), media: 70 },
          { name: "Luton Town", logo: generateLogoPath("Luton Town"), media: 69 },
          { name: "Leeds United", logo: generateLogoPath("Leeds United"), media: 73 },
          { name: "Norwich City", logo: generateLogoPath("Norwich City"), media: 73 },
          { name: "Queens Park Rangers", logo: generateLogoPath("Queens Park Rangers"), media: 72 },
          { name: "Middlesbrough", logo: generateLogoPath("Middlesbrough"), media: 71 },
          { name: "Swansea City", logo: generateLogoPath("Swansea City"), media: 71 },
          { name: "Coventry City", logo: generateLogoPath("Coventry City"), media: 70 },
          { name: "Millwall", logo: generateLogoPath("Millwall"), media: 70 },
          { name: "Hull City", logo: generateLogoPath("Hull City"), media: 70 },
          { name: "Preston North End", logo: generateLogoPath("Preston North End"), media: 70 },
          { name: "Southampton", logo: generateLogoPath("Southampton"), media: 70 },
          { name: "Birmingham City", logo: generateLogoPath("Birmingham City"), media: 69 },
          { name: "Blackburn Rovers", logo: generateLogoPath("Blackburn Rovers"), media: 69 },
          { name: "Bristol City", logo: generateLogoPath("Bristol City"), media: 69 },
          { name: "Stoke City", logo: generateLogoPath("Stoke City"), media: 69 },
          { name: "Sunderland", logo: generateLogoPath("Sunderland"), media: 72 },
          { name: "Huddersfield", logo: generateLogoPath("Huddersfield"), media: 68 },
          { name: "Sheffield Wednesday", logo: generateLogoPath("Sheffield Wednesday"), media: 68 },
          { name: "Derby County", logo: generateLogoPath("Derby County"), media: 67 },
          { name: "Portsmouth", logo: generateLogoPath("Portsmouth"), media: 65 },
          { name: "Ipswich Town", logo: generateLogoPath("Ipswich Town"), media: 70 },
        ],
      },
      {
        id: 49,
        nombre: "League One",
        pais: "Inglaterra",
        categoria: 3,
        teams: [
          { name: "Plymouth Argyle", logo: generateLogoPath("Plymouth Argyle"), media: 67 },
          { name: "Blackpool", logo: generateLogoPath("Blackpool"), media: 66 },
          { name: "Bolton", logo: generateLogoPath("Bolton"), media: 66 },
          { name: "Charlton", logo: generateLogoPath("Charlton"), media: 66 },
          { name: "Reading", logo: generateLogoPath("Reading"), media: 66 },
          { name: "Wigan", logo: generateLogoPath("Wigan"), media: 65 },
          { name: "Wycombe", logo: generateLogoPath("Wycombe"), media: 65 },
          { name: "MK Dons", logo: generateLogoPath("MK Dons"), media: 60 },
          { name: "Wrexham", logo: generateLogoPath("Wrexham"), media: 64 },
          { name: "Salford City", logo: generateLogoPath("Salford City"), media: 59 },
          { name: "AFC Wimbledon", logo: generateLogoPath("AFC Wimbledon"), media: 62 },
          { name: "Port Vale", logo: generateLogoPath("Port Vale"), media: 57 },
          { name: "Rotherham", logo: generateLogoPath("Rotherham"), media: 63 },
          { name: "Stockport", logo: generateLogoPath("Stockport"), media: 64 },
          { name: "Stevenage", logo: generateLogoPath("Stevenage"), media: 61 },
          { name: "Doncaster", logo: generateLogoPath("Doncaster"), media: 59 },
          { name: "Lincoln City", logo: generateLogoPath("Lincoln City"), media: 68 },
          { name: "Bradford City", logo: generateLogoPath("Bradford City"), media: 68 },
          { name: "Mansfield", logo: generateLogoPath("Mansfield"), media: 60 },
          { name: "Leyton Orient", logo: generateLogoPath("Leyton Orient"), media: 63 },
          { name: "Northampton", logo: generateLogoPath("Northampton"), media: 61 },
          { name: "Oxford United", logo: generateLogoPath("Oxford United"), media: 68 },
          { name: "Barnsley", logo: generateLogoPath("Barnsley"), media: 64 },
          { name: "Peterborough", logo: generateLogoPath("Peterborough"), media: 62 },
        ],
      },
    ],
  },
  {
    name: "Internacional",
    leagues: [
      {
        id: 35,
        nombre: "CONMEBOL",
        pais: "Internacional",
        categoria: 1,
        teams: [
          { name: "Argentina", logo: generateLogoPath("Argentina"), media: 87 },
          { name: "Brasil", logo: generateLogoPath("Brasil"), media: 87 },
          { name: "Uruguay", logo: generateLogoPath("Uruguay"), media: 82 },
          { name: "Colombia", logo: generateLogoPath("Colombia"), media: 77 },
          { name: "Ecuador", logo: generateLogoPath("Ecuador"), media: 77 },
          { name: "Chile", logo: generateLogoPath("Chile"), media: 76 },
          { name: "Perú", logo: generateLogoPath("Perú"), media: 76 },
          { name: "Paraguay", logo: generateLogoPath("Paraguay"), media: 74 },
          { name: "Venezuela", logo: generateLogoPath("Venezuela"), media: 71 },
          { name: "Bolivia", logo: generateLogoPath("Bolivia"), media: 68 },
        ],
      },
      {
        id: 36,
        nombre: "CONCACAF",
        pais: "Internacional",
        categoria: 1,
        teams: [
          { name: "Estados Unidos", logo: generateLogoPath("Estados Unidos"), media: 80 },
          { name: "México", logo: generateLogoPath("México"), media: 77 },
          { name: "Costa Rica", logo: generateLogoPath("Costa Rica"), media: 74 },
          { name: "Canadá", logo: generateLogoPath("Canadá"), media: 73 },
          { name: "Panamá", logo: generateLogoPath("Panamá"), media: 69 },
          { name: "Honduras", logo: generateLogoPath("Honduras"), media: 67 },
          { name: "Jamaica", logo: generateLogoPath("Jamaica"), media: 67 },
          { name: "El Salvador", logo: generateLogoPath("El Salvador"), media: 60 },
          { name: "Belice", logo: generateLogoPath("Belice"), media: 44 },
          { name: "Guatemala", logo: generateLogoPath("Guatemala"), media: 63 },
          { name: "Nicaragua", logo: generateLogoPath("Nicaragua"), media: 63 },
          { name: "Groenlandia", logo: generateLogoPath("Groenlandia"), media: 40 },
          { name: "Anguila", logo: generateLogoPath("Anguila"), media: 26 },
          { name: "Antigua y Barbuda", logo: generateLogoPath("Antigua y Barbuda"), media: 38 },
          { name: "Aruba", logo: generateLogoPath("Aruba"), media: 41 },
          { name: "Bahamas", logo: generateLogoPath("Bahamas"), media: 33 },
          { name: "Barbados", logo: generateLogoPath("Barbados"), media: 42 },
          { name: "Bermudas", logo: generateLogoPath("Bermudas"), media: 55 },
          { name: "Bonaire", logo: generateLogoPath("Bonaire"), media: 32 },
          { name: "Cuba", logo: generateLogoPath("Cuba"), media: 57 },
          { name: "Curazao", logo: generateLogoPath("Curazao"), media: 56 },
          { name: "Dominica", logo: generateLogoPath("Dominica"), media: 36 },
          { name: "Granada", logo: generateLogoPath("Granada"), media: 44 },
          { name: "Guadalupe", logo: generateLogoPath("Guadalupe"), media: 51 },
          { name: "Guyana", logo: generateLogoPath("Guyana"), media: 46 },
          { name: "Guayana Francesa", logo: generateLogoPath("Guayana Francesa"), media: 52 },
          { name: "Haití", logo: generateLogoPath("Haití"), media: 59 },
          { name: "Islas Caimán", logo: generateLogoPath("Islas Caimán"), media: 35 },
          { name: "Islas Turcas y Caicos", logo: generateLogoPath("Islas Turcas y Caicos"), media: 29 },
          { name: "Islas Vírgenes Británicas", logo: generateLogoPath("Islas Vírgenes Británicas"), media: 28 },
          { name: "Islas Vírgenes Estadounidenses", logo: generateLogoPath("Islas Vírgenes Estadounidenses"), media: 30 },
          { name: "Martinica", logo: generateLogoPath("Martinica"), media: 56 },
          { name: "Montserrat", logo: generateLogoPath("Montserrat"), media: 25 },
          { name: "Puerto Rico", logo: generateLogoPath("Puerto Rico"), media: 51 },
          { name: "República Dominicana", logo: generateLogoPath("República Dominicana"), media: 56 },
          { name: "Saint-Martin", logo: generateLogoPath("Saint-Martin"), media: 42 },
          { name: "San Cristóbal y Nieves", logo: generateLogoPath("San Cristóbal y Nieves"), media: 39 },
          { name: "San Vicente y las Granadinas", logo: generateLogoPath("San Vicente y las Granadinas"), media: 51 },
          { name: "Sint Maarten", logo: generateLogoPath("Sint Maarten"), media: 48 },
          { name: "Surinam", logo: generateLogoPath("Surinam"), media: 64 },
          { name: "Trinidad y Tobago", logo: generateLogoPath("Trinidad y Tobago"), media: 59 },
          { name: "Santa Lucía", logo: generateLogoPath("Santa Lucía"), media: 48 },
        ],
      },
      {
        id: 37,
        nombre: "UEFA",
        pais: "Internacional",
        categoria: 1,
        teams: [
          { name: "Francia", logo: generateLogoPath("Francia"), media: 87 },
          { name: "España", logo: generateLogoPath("España"), media: 86 },
          { name: "Inglaterra", logo: generateLogoPath("Inglaterra"), media: 84 },
          { name: "Croacia", logo: generateLogoPath("Croacia"), media: 83 },
          { name: "Portugal", logo: generateLogoPath("Portugal"), media: 83 },
          { name: "Alemania", logo: generateLogoPath("Alemania"), media: 82 },
          { name: "Bélgica", logo: generateLogoPath("Bélgica"), media: 82 },
          { name: "Italia", logo: generateLogoPath("Italia"), media: 82 },
          { name: "Países Bajos", logo: generateLogoPath("Países Bajos"), media: 82 },
          { name: "Suiza", logo: generateLogoPath("Suiza"), media: 80 },
          { name: "Rusia", logo: generateLogoPath("Rusia"), media: 79 },
          { name: "Serbia", logo: generateLogoPath("Serbia"), media: 79 },
          { name: "Dinamarca", logo: generateLogoPath("Dinamarca"), media: 78 },
          { name: "Noruega", logo: generateLogoPath("Noruega"), media: 78 },
          { name: "Polonia", logo: generateLogoPath("Polonia"), media: 77 },
          { name: "Austria", logo: generateLogoPath("Austria"), media: 76 },
          { name: "República Checa", logo: generateLogoPath("República Checa"), media: 76 },
          { name: "Suecia", logo: generateLogoPath("Suecia"), media: 76 },
          { name: "Escocia", logo: generateLogoPath("Escocia"), media: 75 },
          { name: "Ucrania", logo: generateLogoPath("Ucrania"), media: 75 },
          { name: "Georgia", logo: generateLogoPath("Georgia"), media: 74 },
          { name: "Turquía", logo: generateLogoPath("Turquía"), media: 74 },
          { name: "Albania", logo: generateLogoPath("Albania"), media: 73 },
          { name: "Gales", logo: generateLogoPath("Gales"), media: 73 },
          { name: "Hungría", logo: generateLogoPath("Hungría"), media: 73 },
          { name: "Grecia", logo: generateLogoPath("Grecia"), media: 72 },
          { name: "Irlanda", logo: generateLogoPath("Irlanda"), media: 72 },
          { name: "Finlandia", logo: generateLogoPath("Finlandia"), media: 71 },
          { name: "Rumania", logo: generateLogoPath("Rumania"), media: 71 },
          { name: "Islandia", logo: generateLogoPath("Islandia"), media: 73 },
          { name: "Macedonia del Norte", logo: generateLogoPath("Macedonia del Norte"), media: 70 },
          { name: "Eslovenia", logo: generateLogoPath("Eslovenia"), media: 68 },
          { name: "Israel", logo: generateLogoPath("Israel"), media: 68 },
          { name: "Irlanda del Norte", logo: generateLogoPath("Irlanda del Norte"), media: 67 },
          { name: "Eslovaquia", logo: generateLogoPath("Eslovaquia"), media: 65 },
          { name: "Armenia", logo: generateLogoPath("Armenia"), media: 64 },
          { name: "Bosnia y Herzegovina", logo: generateLogoPath("Bosnia y Herzegovina"), media: 64 },
          { name: "Bulgaria", logo: generateLogoPath("Bulgaria"), media: 64 },
          { name: "Azerbaiyán", logo: generateLogoPath("Azerbaiyán"), media: 62 },
          { name: "Bielorrusia", logo: generateLogoPath("Bielorrusia"), media: 61 },
          { name: "Kazajistán", logo: generateLogoPath("Kazajistán"), media: 61 },
          { name: "Moldavia", logo: generateLogoPath("Moldavia"), media: 61 },
          { name: "Montenegro", logo: generateLogoPath("Montenegro"), media: 60 },
          { name: "Lituania", logo: generateLogoPath("Lituania"), media: 59 },
          { name: "Chipre", logo: generateLogoPath("Chipre"), media: 58 },
          { name: "Estonia", logo: generateLogoPath("Estonia"), media: 57 },
          { name: "Kosovo", logo: generateLogoPath("Kosovo"), media: 57 },
          { name: "Letonia", logo: generateLogoPath("Letonia"), media: 55 },
          { name: "Islas Feroe", logo: generateLogoPath("Islas Feroe"), media: 62 },
          { name: "Luxemburgo", logo: generateLogoPath("Luxemburgo"), media: 48 },
          { name: "Malta", logo: generateLogoPath("Malta"), media: 45 },
          { name: "Gibraltar", logo: generateLogoPath("Gibraltar"), media: 43 },
          { name: "Andorra", logo: generateLogoPath("Andorra"), media: 41 },
          { name: "Liechtenstein", logo: generateLogoPath("Liechtenstein"), media: 39 },
          { name: "San Marino", logo: generateLogoPath("San Marino"), media: 41 },
        ],
      },
      {
        id: 38,
        nombre: "OFC",
        pais: "Internacional",
        categoria: 1,
        teams: [
          { name: "Nueva Zelanda", logo: generateLogoPath("Nueva Zelanda"), media: 66 },
          { name: "Islas Salomón", logo: generateLogoPath("Islas Salomón"), media: 44 },
          { name: "Nueva Caledonia", logo: generateLogoPath("Nueva Caledonia"), media: 51 },
          { name: "Tahití", logo: generateLogoPath("Tahití"), media: 45 },
          { name: "Fiji", logo: generateLogoPath("Fiji"), media: 44 },
          { name: "Vanuatu", logo: generateLogoPath("Vanuatu"), media: 46 },
          { name: "Papúa Nueva Guinea", logo: generateLogoPath("Papúa Nueva Guinea"), media: 49 },
          { name: "Samoa", logo: generateLogoPath("Samoa"), media: 41 },
          { name: "Islas Cook", logo: generateLogoPath("Islas Cook"), media: 31 },
          { name: "Samoa Americana", logo: generateLogoPath("Samoa Americana"), media: 36 },
          { name: "Tonga", logo: generateLogoPath("Tonga"), media: 39 },
          { name: "Tuvalu", logo: generateLogoPath("Tuvalu"), media: 30 },
          { name: "Kiribati", logo: generateLogoPath("Kiribati"), media: 17 },
          { name: "Islas Marshall", logo: generateLogoPath("Islas Marshall"), media: 14 },
          { name: "Micronesia", logo: generateLogoPath("Micronesia"), media: 1 },
          { name: "Palaos", logo: generateLogoPath("Palaos"), media: 1 },
          { name: "Nauru", logo: generateLogoPath("Nauru"), media: 1 },
          { name: "Wallis y Futuna", logo: generateLogoPath("Wallis y Futuna"), media: 1 },
          { name: "Niue", logo: generateLogoPath("Niue"), media: 1 },
          { name: "Tokelau", logo: generateLogoPath("Tokelau"), media: 1 },
        ],
      },
      {
        id: 39,
        nombre: "CAF",
        pais: "Internacional",
        categoria: 1,
        teams: [
          { name: "Senegal", logo: generateLogoPath("Senegal"), media: 80 },
          { name: "Argelia", logo: generateLogoPath("Argelia"), media: 77 },
          { name: "Marruecos", logo: generateLogoPath("Marruecos"), media: 77 },
          { name: "Egipto", logo: generateLogoPath("Egipto"), media: 76 },
          { name: "Camerún", logo: generateLogoPath("Camerún"), media: 75 },
          { name: "Ghana", logo: generateLogoPath("Ghana"), media: 75 },
          { name: "Nigeria", logo: generateLogoPath("Nigeria"), media: 75 },
          { name: "Túnez", logo: generateLogoPath("Túnez"), media: 75 },
          { name: "Costa de Marfil", logo: generateLogoPath("Costa de Marfil"), media: 75 },
          { name: "R. D. del Congo", logo: generateLogoPath("R. D. del Congo"), media: 73 },
          { name: "Guinea", logo: generateLogoPath("Guinea"), media: 65 },
          { name: "Sudáfrica", logo: generateLogoPath("Sudáfrica"), media: 70 },
          { name: "Burkina Faso", logo: generateLogoPath("Burkina Faso"), media: 68 },
          { name: "Malí", logo: generateLogoPath("Malí"), media: 67 },
          { name: "Gabón", logo: generateLogoPath("Gabón"), media: 65 },
          { name: "Uganda", logo: generateLogoPath("Uganda"), media: 64 },
          { name: "Libia", logo: generateLogoPath("Libia"), media: 57 },
          { name: "Cabo Verde", logo: generateLogoPath("Cabo Verde"), media: 62 },
          { name: "Gambia", logo: generateLogoPath("Gambia"), media: 62 },
          { name: "Guinea Bissau", logo: generateLogoPath("Guinea Bissau"), media: 60 },
          { name: "Guinea Ecuatorial", logo: generateLogoPath("Guinea Ecuatorial"), media: 58 },
          { name: "Liberia", logo: generateLogoPath("Liberia"), media: 61 },
          { name: "Mauritania", logo: generateLogoPath("Mauritania"), media: 55 },
          { name: "Sierra Leona", logo: generateLogoPath("Sierra Leona"), media: 62 },
          { name: "Benín", logo: generateLogoPath("Benín"), media: 63 },
          { name: "Níger", logo: generateLogoPath("Níger"), media: 61 },
          { name: "Togo", logo: generateLogoPath("Togo"), media: 59 },
          { name: "Chad", logo: generateLogoPath("Chad"), media: 51 },
          { name: "Congo", logo: generateLogoPath("Congo"), media: 60 },
          { name: "República Centroafricana", logo: generateLogoPath("República Centroafricana"), media: 62 },
          { name: "Santo Tomé y Príncipe", logo: generateLogoPath("Santo Tomé y Príncipe"), media: 52 },
          { name: "Burundi", logo: generateLogoPath("Burundi"), media: 56 },
          { name: "Eritrea", logo: generateLogoPath("Eritrea"), media: 59 },
          { name: "Etiopía", logo: generateLogoPath("Etiopía"), media: 59 },
          { name: "Kenia", logo: generateLogoPath("Kenia"), media: 57 },
          { name: "Ruanda", logo: generateLogoPath("Ruanda"), media: 53 },
          { name: "Somalia", logo: generateLogoPath("Somalia"), media: 50 },
          { name: "Sudán", logo: generateLogoPath("Sudán"), media: 61 },
          { name: "Sudán del Sur", logo: generateLogoPath("Sudán del Sur"), media: 49 },
          { name: "Tanzania", logo: generateLogoPath("Tanzania"), media: 58 },
          { name: "Yibuti", logo: generateLogoPath("Yibuti"), media: 53 },
          { name: "Angola", logo: generateLogoPath("Angola"), media: 59 },
          { name: "Botswana", logo: generateLogoPath("Botswana"), media: 58 },
          { name: "Comores", logo: generateLogoPath("Comores"), media: 60 },
          { name: "Esuatini", logo: generateLogoPath("Esuatini"), media: 46 },
          { name: "Lesoto", logo: generateLogoPath("Lesoto"), media: 51 },
          { name: "Madagascar", logo: generateLogoPath("Madagascar"), media: 64 },
          { name: "Malawi", logo: generateLogoPath("Malawi"), media: 56 },
          { name: "Mauricio", logo: generateLogoPath("Mauricio"), media: 47 },
          { name: "Mozambique", logo: generateLogoPath("Mozambique"), media: 63 },
          { name: "Namibia", logo: generateLogoPath("Namibia"), media: 61 },
          { name: "Seychelles", logo: generateLogoPath("Seychelles"), media: 43 },
          { name: "Zambia", logo: generateLogoPath("Zambia"), media: 63 },
          { name: "Zimbabwe", logo: generateLogoPath("Zimbabwe"), media: 53 },
        ],
      },
      {
        id: 40,
        nombre: "AFC",
        pais: "Internacional",
        categoria: 1,
        teams: [
          { name: "Japón", logo: generateLogoPath("Japón"), media: 79 },
          { name: "Australia", logo: generateLogoPath("Australia"), media: 78 },
          { name: "Arabia Saudita", logo: generateLogoPath("Arabia Saudita"), media: 77 },
          { name: "Corea del Sur", logo: generateLogoPath("Corea del Sur"), media: 76 },
          { name: "Irán", logo: generateLogoPath("Irán"), media: 71 },
          { name: "Qatar", logo: generateLogoPath("Qatar"), media: 70 },
          { name: "China", logo: generateLogoPath("China"), media: 65 },
          { name: "Emiratos Árabes Unidos", logo: generateLogoPath("Emiratos Árabes Unidos"), media: 67 },
          { name: "Irak", logo: generateLogoPath("Irak"), media: 66 },
          { name: "Uzbekistán", logo: generateLogoPath("Uzbekistán"), media: 66 },
          { name: "Siria", logo: generateLogoPath("Siria"), media: 64 },
          { name: "Omán", logo: generateLogoPath("Omán"), media: 62 },
          { name: "Vietnam", logo: generateLogoPath("Vietnam"), media: 54 },
          { name: "Malasia", logo: generateLogoPath("Malasia"), media: 59 },
          { name: "Corea del Norte", logo: generateLogoPath("Corea del Norte"), media: 64 },
          { name: "Birmania", logo: generateLogoPath("Birmania"), media: 47 },
          { name: "Brunei", logo: generateLogoPath("Brunei"), media: 48 },
          { name: "Camboya", logo: generateLogoPath("Camboya"), media: 47 },
          { name: "Filipinas", logo: generateLogoPath("Filipinas"), media: 49 },
          { name: "Indonesia", logo: generateLogoPath("Indonesia"), media: 58 },
          { name: "Laos", logo: generateLogoPath("Laos"), media: 50 },
          { name: "Turkmenistán", logo: generateLogoPath("Turkmenistán"), media: 55 },
          { name: "Singapur", logo: generateLogoPath("Singapur"), media: 52 },
          { name: "Tailandia", logo: generateLogoPath("Tailandia"), media: 63 },
          { name: "Timor Oriental", logo: generateLogoPath("Timor Oriental"), media: 46 },
          { name: "Bahrein", logo: generateLogoPath("Bahrein"), media: 61 },
          { name: "Jordania", logo: generateLogoPath("Jordania"), media: 68 },
          { name: "Palestina", logo: generateLogoPath("Palestina"), media: 57 },
          { name: "Kirguistán", logo: generateLogoPath("Kirguistán"), media: 61 },
          { name: "India", logo: generateLogoPath("India"), media: 52 },
          { name: "Líbano", logo: generateLogoPath("Líbano"), media: 56 },
          { name: "Tayikistán", logo: generateLogoPath("Tayikistán"), media: 61 },
          { name: "Kuwait", logo: generateLogoPath("Kuwait"), media: 53 },
          { name: "Hong Kong", logo: generateLogoPath("Hong Kong"), media: 51 },
          { name: "China Taipei", logo: generateLogoPath("China Taipei"), media: 49 },
          { name: "Maldivas", logo: generateLogoPath("Maldivas"), media: 44 },
          { name: "Yemen", logo: generateLogoPath("Yemen"), media: 52 },
          { name: "Afganistán", logo: generateLogoPath("Afganistán"), media: 48 },
          { name: "Macao", logo: generateLogoPath("Macao"), media: 50 },
          { name: "Mongolia", logo: generateLogoPath("Mongolia"), media: 46 },
          { name: "Bután", logo: generateLogoPath("Bután"), media: 35 },
          { name: "Bangladesh", logo: generateLogoPath("Bangladesh"), media: 49 },
          { name: "Pakistán", logo: generateLogoPath("Pakistán"), media: 49 },
          { name: "Guam", logo: generateLogoPath("Guam"), media: 42 },
          { name: "Sri Lanka", logo: generateLogoPath("Sri Lanka"), media: 51 },
          { name: "Nepal", logo: generateLogoPath("Nepal"), media: 53 },
          { name: "Islas Marianas del Norte", logo: generateLogoPath("Islas Marianas del Norte"), media: 27 },
        ],
      },
    ],
  },
  {
    name: "Islandia",
    leagues: [
      {
        id: 11,
        nombre: "Besta deild",
        pais: "Islandia",
        categoria: 1,
        teams: [
          { name: "Valur", logo: generateLogoPath("Valur"), media: 99 },
          { name: "Breidablik", logo: generateLogoPath("Breidablik"), media: 61 },
          { name: "FH", logo: generateLogoPath("FH"), media: 57 },
          { name: "Fram", logo: generateLogoPath("Fram"), media: 53 },
          { name: "Vestri", logo: generateLogoPath("Vestri"), media: 57 },
          { name: "IBV", logo: generateLogoPath("IBV"), media: 54 },
          { name: "KA", logo: generateLogoPath("KA"), media: 55 },
          { name: "Keflavik", logo: generateLogoPath("Keflavik"), media: 52 },
          { name: "KR", logo: generateLogoPath("KR"), media: 59 },
          { name: "Stjarnan", logo: generateLogoPath("Stjarnan"), media: 57 },
          { name: "Vikingur", logo: generateLogoPath("Vikingur"), media: 62 },
          { name: "ÍA", logo: generateLogoPath("ÍA"), media: 54 },
        ],
      },
      {
        id: 26,
        nombre: "1. deild karla",
        pais: "Islandia",
        categoria: 2,
        teams: [
          { name: "Fylkir", logo: generateLogoPath("Fylkir"), media: 49 },
          { name: "ÍR", logo: generateLogoPath("ÍR"), media: 46 },
          { name: "Afturelding", logo: generateLogoPath("Afturelding"), media: 51 },
          { name: "Fjolnir", logo: generateLogoPath("Fjolnir"), media: 50 },
          { name: "Grindavik", logo: generateLogoPath("Grindavik"), media: 51 },
          { name: "Grotta", logo: generateLogoPath("Grotta"), media: 49 },
          { name: "Leiknir R", logo: generateLogoPath("Leiknir R"), media: 49 },
          { name: "Njardvik", logo: generateLogoPath("Njardvik"), media: 52 },
          { name: "Selfoss", logo: generateLogoPath("Selfoss"), media: 50 },
          { name: "Thor", logo: generateLogoPath("Thor"), media: 49 },
          { name: "Throttur", logo: generateLogoPath("Throttur"), media: 51 },
          { name: "HK", logo: generateLogoPath("HK"), media: 54 },
        ],
      },
    ],
  },
  {
    name: "Italia",
    leagues: [
      {
        id: 5,
        nombre: "Serie A",
        pais: "Italia",
        categoria: 1,
        teams: [
          { name: "Juventus", logo: generateLogoPath("Juventus"), media: 83 },
          { name: "Inter", logo: generateLogoPath("Inter"), media: 86 },
          { name: "Milan", logo: generateLogoPath("Milan"), media: 84 },
          { name: "Napoli", logo: generateLogoPath("Napoli"), media: 84 },
          { name: "Roma", logo: generateLogoPath("Roma"), media: 82 },
          { name: "Lazio", logo: generateLogoPath("Lazio"), media: 78 },
          { name: "Atalanta", logo: generateLogoPath("Atalanta"), media: 80 },
          { name: "Fiorentina", logo: generateLogoPath("Fiorentina"), media: 75 },
          { name: "Torino", logo: generateLogoPath("Torino"), media: 74 },
          { name: "Bologna", logo: generateLogoPath("Bologna"), media: 77 },
          { name: "Udinese", logo: generateLogoPath("Udinese"), media: 76 },
          { name: "Sassuolo", logo: generateLogoPath("Sassuolo"), media: 75 },
          { name: "Monza", logo: generateLogoPath("Monza"), media: 70 },
          { name: "Empoli", logo: generateLogoPath("Empoli"), media: 73 },
          { name: "Salernitana", logo: generateLogoPath("Salernitana"), media: 69 },
          { name: "Lecce", logo: generateLogoPath("Lecce"), media: 70 },
          { name: "Hellas Verona", logo: generateLogoPath("Hellas Verona"), media: 71 },
          { name: "Sampdoria", logo: generateLogoPath("Sampdoria"), media: 70 },
          { name: "Cremonese", logo: generateLogoPath("Cremonese"), media: 73 },
          { name: "Spezia", logo: generateLogoPath("Spezia"), media: 66 },
        ],
      },
      {
        id: 28,
        nombre: "Serie B",
        pais: "Italia",
        categoria: 2,
        teams: [
          { name: "Genoa", logo: generateLogoPath("Genoa"), media: 73 },
          { name: "Cagliari", logo: generateLogoPath("Cagliari"), media: 69 },
          { name: "Frosinone", logo: generateLogoPath("Frosinone"), media: 68 },
          { name: "Parma", logo: generateLogoPath("Parma"), media: 72 },
          { name: "Venezia", logo: generateLogoPath("Venezia"), media: 67 },
          { name: "Brescia", logo: generateLogoPath("Brescia"), media: 68 },
          { name: "Pisa", logo: generateLogoPath("Pisa"), media: 71 },
          { name: "Bari", logo: generateLogoPath("Bari"), media: 65 },
          { name: "Como", logo: generateLogoPath("Como"), media: 73 },
          { name: "Palermo", logo: generateLogoPath("Palermo"), media: 71 },
          { name: "Crotone", logo: generateLogoPath("Crotone"), media: 65 },
          { name: "Pescara", logo: generateLogoPath("Pescara"), media: 62 },
          { name: "Südtirol", logo: generateLogoPath("Südtirol"), media: 67 },
          { name: "Catania", logo: generateLogoPath("Catania"), media: 61 },
          { name: "Avellino", logo: generateLogoPath("Avellino"), media: 65 },
          { name: "Catanzaro", logo: generateLogoPath("Catanzaro"), media: 66 },
          { name: "Reggiana", logo: generateLogoPath("Reggiana"), media: 65 },
          { name: "Juve Stabia", logo: generateLogoPath("Juve Stabia"), media: 66 },
          { name: "Carrarese", logo: generateLogoPath("Carrarese"), media: 64 },
          { name: "Virtus Entella", logo: generateLogoPath("Virtus Entella"), media: 63 },
        ],
      },
      {
        id: 52,
        nombre: "Serie C",
        pais: "Italia",
        categoria: 3,
        teams: [
          { name: "SPAL", logo: generateLogoPath("SPAL"), media: 62 },
          { name: "Siena", logo: generateLogoPath("Siena"), media: 61 },
          { name: "Benevento", logo: generateLogoPath("Benevento"), media: 59 },
          { name: "Reggina", logo: generateLogoPath("Reggina"), media: 60 },
          { name: "AlbinoLeffe", logo: generateLogoPath("AlbinoLeffe"), media: 63 },
          { name: "Ascoli", logo: generateLogoPath("Ascoli"), media: 60 },
          { name: "Cittadella", logo: generateLogoPath("Cittadella"), media: 59 },
          { name: "Cosenza", logo: generateLogoPath("Cosenza"), media: 58 },
          { name: "Messina", logo: generateLogoPath("Messina"), media: 60 },
          { name: "Carpi", logo: generateLogoPath("Carpi"), media: 62 },
          { name: "Cesena", logo: generateLogoPath("Cesena"), media: 56 },
          { name: "Modena", logo: generateLogoPath("Modena"), media: 66 },
          { name: "Piacenza", logo: generateLogoPath("Piacenza"), media: 63 },
          { name: "Ternana", logo: generateLogoPath("Ternana"), media: 59 },
          { name: "Padova", logo: generateLogoPath("Padova"), media: 61 },
          { name: "Lecco", logo: generateLogoPath("Lecco"), media: 62 },
          { name: "Perugia", logo: generateLogoPath("Perugia"), media: 64 },
          { name: "Livorno", logo: generateLogoPath("Livorno"), media: 57 },
          { name: "Treviso", logo: generateLogoPath("Treviso"), media: 51 },
          { name: "Chievo Verona", logo: generateLogoPath("Chievo Verona"), media: 62 },
        ],
      },
    ],
  },
  {
    name: "México",
    leagues: [
      {
        id: 8,
        nombre: "Liga MX",
        pais: "México",
        categoria: 1,
        teams: [
          { name: "América", logo: generateLogoPath("América"), media: 75 },
          { name: "Chivas", logo: generateLogoPath("Chivas"), media: 73 },
          { name: "Cruz Azul", logo: generateLogoPath("Cruz Azul"), media: 74 },
          { name: "Monterrey", logo: generateLogoPath("Monterrey"), media: 76 },
          { name: "Pachuca", logo: generateLogoPath("Pachuca"), media: 73 },
          { name: "Pumas", logo: generateLogoPath("Pumas"), media: 74 },
          { name: "Tigres", logo: generateLogoPath("Tigres"), media: 77 },
          { name: "Toluca", logo: generateLogoPath("Toluca"), media: 74 },
          { name: "Tijuana", logo: generateLogoPath("Tijuana"), media: 71 },
          { name: "Juárez", logo: generateLogoPath("Juárez"), media: 69 },
          { name: "Santos Laguna", logo: generateLogoPath("Santos Laguna"), media: 69 },
          { name: "Querétaro", logo: generateLogoPath("Querétaro"), media: 68 },
          { name: "Necaxa", logo: generateLogoPath("Necaxa"), media: 66 },
          { name: "Atlas", logo: generateLogoPath("Atlas"), media: 68 },
          { name: "Atlético San Luis", logo: generateLogoPath("Atlético San Luis"), media: 65 },
          { name: "Mazatlán", logo: generateLogoPath("Mazatlán"), media: 63 },
          { name: "León", logo: generateLogoPath("León"), media: 67 },
          { name: "Puebla", logo: generateLogoPath("Puebla"), media: 66 },
        ],
      },
    ],
  },
  {
    name: "Países Bajos",
    leagues: [
      {
        id: 10,
        nombre: "Eredivisie",
        pais: "Países Bajos",
        categoria: 1,
        teams: [
          { name: "PSV", logo: generateLogoPath("PSV"), media: 79 },
          { name: "Ajax", logo: generateLogoPath("Ajax"), media: 76 },
          { name: "Feyenoord", logo: generateLogoPath("Feyenoord"), media: 76 },
          { name: "AZ Alkmaar", logo: generateLogoPath("AZ Alkmaar"), media: 73 },
          { name: "Twente", logo: generateLogoPath("Twente"), media: 71 },
          { name: "NEC Nijmegen", logo: generateLogoPath("NEC Nijmegen"), media: 71 },
          { name: "Utrecht", logo: generateLogoPath("Utrecht"), media: 73 },
          { name: "Go Ahead Eagles", logo: generateLogoPath("Go Ahead Eagles"), media: 69 },
          { name: "Sparta Rotterdam", logo: generateLogoPath("Sparta Rotterdam"), media: 69 },
          { name: "Fortuna Sittard", logo: generateLogoPath("Fortuna Sittard"), media: 68 },
          { name: "Groningen", logo: generateLogoPath("Groningen"), media: 68 },
          { name: "Heerenveen", logo: generateLogoPath("Heerenveen"), media: 68 },
          { name: "NAC Breda", logo: generateLogoPath("NAC Breda"), media: 67 },
          { name: "PEC Zwolle", logo: generateLogoPath("PEC Zwolle"), media: 66 },
          { name: "Excelsior", logo: generateLogoPath("Excelsior"), media: 66 },
          { name: "Heracles Almelo", logo: generateLogoPath("Heracles Almelo"), media: 66 },
          { name: "Volendam", logo: generateLogoPath("Volendam"), media: 65 },
          { name: "Telstar", logo: generateLogoPath("Telstar"), media: 65 },
        ],
      },
    ],
  },
  {
    name: "Paraguay",
    leagues: [
      {
        id: 20,
        nombre: "Primera División",
        pais: "Paraguay",
        categoria: 1,
        teams: [
          { name: "Olimpia", logo: generateLogoPath("Olimpia"), media: 67 },
          { name: "Nacional (Par)", logo: generateLogoPath("Nacional (Par)"), media: 62 },
          { name: "Cerro Porteño", logo: generateLogoPath("Cerro Porteño"), media: 69 },
          { name: "Libertad", logo: generateLogoPath("Libertad"), media: 71 },
          { name: "Guaraní", logo: generateLogoPath("Guaraní"), media: 65 },
          { name: "2 de Mayo", logo: generateLogoPath("2 de Mayo"), media: 60 },
          { name: "Recoleta", logo: generateLogoPath("Recoleta"), media: 62 },
          { name: "Sportivo Luqueño", logo: generateLogoPath("Sportivo Luqueño"), media: 62 },
          { name: "Trinidense", logo: generateLogoPath("Trinidense"), media: 65 },
          { name: "Sportivo Ameliano", logo: generateLogoPath("Sportivo Ameliano"), media: 63 },
          { name: "Rubio Ñu", logo: generateLogoPath("Rubio Ñu"), media: 59 },
          { name: "San Lorenzo (Par)", logo: generateLogoPath("San Lorenzo (Par)"), media: 58 },
        ],
      },
    ],
  },
  {
    name: "Portugal",
    leagues: [
      {
        id: 9,
        nombre: "Liga Portuguesa",
        pais: "Portugal",
        categoria: 1,
        teams: [
          { name: "Benfica", logo: generateLogoPath("Benfica"), media: 81 },
          { name: "Sporting Lisboa", logo: generateLogoPath("Sporting Lisboa"), media: 80 },
          { name: "Porto", logo: generateLogoPath("Porto"), media: 82 },
          { name: "Sporting Braga", logo: generateLogoPath("Sporting Braga"), media: 75 },
          { name: "Famalicão", logo: generateLogoPath("Famalicão"), media: 70 },
          { name: "Casa Pia", logo: generateLogoPath("Casa Pia"), media: 66 },
          { name: "Santa Clara", logo: generateLogoPath("Santa Clara"), media: 70 },
          { name: "Estoril", logo: generateLogoPath("Estoril"), media: 70 },
          { name: "Rio Ave", logo: generateLogoPath("Rio Ave"), media: 69 },
          { name: "Arouca", logo: generateLogoPath("Arouca"), media: 67 },
          { name: "Moreirense", logo: generateLogoPath("Moreirense"), media: 70 },
          { name: "Aves", logo: generateLogoPath("Aves"), media: 62 },
          { name: "Gil Vicente", logo: generateLogoPath("Gil Vicente"), media: 71 },
          { name: "Vitória Guimarães", logo: generateLogoPath("Vitória Guimarães"), media: 70 },
          { name: "Tondela", logo: generateLogoPath("Tondela"), media: 64 },
          { name: "Alverca", logo: generateLogoPath("Alverca"), media: 66 },
          { name: "Nacional de Madeira", logo: generateLogoPath("Nacional de Madeira"), media: 67 },
          { name: "Estrela da Amadora", logo: generateLogoPath("Estrela da Amadora"), media: 66 },
        ],
      },
    ],
  },
  {
    name: "Uruguay",
    leagues: [
      {
        id: 17,
        nombre: "Liga AUF Uruguaya",
        pais: "Uruguay",
        categoria: 1,
        teams: [
          { name: "Peñarol", logo: generateLogoPath("Peñarol"), media: 72 },
          { name: "Nacional", logo: generateLogoPath("Nacional"), media: 71 },
          { name: "Montevideo City Torque", logo: generateLogoPath("Montevideo City Torque"), media: 67 },
          { name: "Boston River", logo: generateLogoPath("Boston River"), media: 66 },
          { name: "Cerro Largo", logo: generateLogoPath("Cerro Largo"), media: 65 },
          { name: "Liverpool (U)", logo: generateLogoPath("Liverpool (U)"), media: 67 },
          { name: "Cerro", logo: generateLogoPath("Cerro"), media: 64 },
          { name: "Defensor Sporting", logo: generateLogoPath("Defensor Sporting"), media: 65 },
          { name: "Danubio", logo: generateLogoPath("Danubio"), media: 66 },
          { name: "Progreso", logo: generateLogoPath("Progreso"), media: 63 },
          { name: "Racing (Montevideo)", logo: generateLogoPath("Racing (Montevideo)"), media: 64 },
          { name: "Juventud de Las Piedras", logo: generateLogoPath("Juventud de Las Piedras"), media: 62 },
          { name: "River Plate (U)", logo: generateLogoPath("River Plate (U)"), media: 60 },
          { name: "Miramar Misiones", logo: generateLogoPath("Miramar Misiones"), media: 59 },
          { name: "Plaza Colonia", logo: generateLogoPath("Plaza Colonia"), media: 61 },
          { name: "Montevideo Wanderers", logo: generateLogoPath("Montevideo Wanderers"), media: 62 },
        ],
      },
    ],
  },
];

  useEffect(() => {
  // en lugar de fetch, uso los hardcodeados
  setCountries(hardcodedCountries);
}, [])

/*   useEffect(() => {
    const fetchData = async () => {
      try {
        const ligasResponse = await fetch("https://localhost:7225/api/ligas");
        const equiposResponse = await fetch("https://localhost:7225/api/equipos");

        const ligas: League[] = await ligasResponse.json();
        const equipos = await equiposResponse.json();

        const ligasConEquipos: League[] = ligas.map((liga) => ({
          ...liga,
          teams: equipos
            .filter((eq: any) => eq.ligaId === liga.id)
            .map((eq: any) => ({
              name: eq.nombre,
              media: eq.media,
              logo: generateLogoPath(eq.nombre),
            })),
        }));

        const agrupadoPorPais: Country[] = [];
        ligasConEquipos.forEach((liga) => {
          const paisExistente = agrupadoPorPais.find((c) => c.name === liga.pais);
          if (paisExistente) {
            paisExistente.leagues.push(liga);
          } else {
            agrupadoPorPais.push({ name: liga.pais, leagues: [liga] });
          }
        });

        agrupadoPorPais.sort((a, b) => a.name.localeCompare(b.name));
        agrupadoPorPais.forEach((pais) => {
          pais.leagues.sort((a, b) => a.categoria - b.categoria);
        });

        setCountries(agrupadoPorPais);
      } catch (error) {
        console.error("Error al cargar datos:", error);
      }
    };

    fetchData();
  }, []); */

  const handleSeleccion = (equipo: Team) => {
    onSelectedTeam(equipo);
  };

  const siguientePais = () => {
    setSelectedCountryIndex((prev) => (prev + 1) % countries.length);
    setSelectedLeagueIndex(0);
  };

  const anteriorPais = () => {
    setSelectedCountryIndex((prev) => (prev - 1 + countries.length) % countries.length);
    setSelectedLeagueIndex(0);
  };

  const siguienteLiga = () => {
    if (!selectedCountry) return;
    setSelectedLeagueIndex((prev) => (prev + 1) % selectedCountry.leagues.length);
  };

  const anteriorLiga = () => {
    if (!selectedCountry) return;
    setSelectedLeagueIndex((prev) => (prev - 1 + selectedCountry.leagues.length) % selectedCountry.leagues.length);
  };

  return (
    <div className="selector-equipos">
      {/* Navegación de países */}
      <div className="paises-navegacion">
        <button onClick={anteriorPais} disabled={countries.length <= 1}>{"<"}</button>
        <span>{selectedCountry?.name}</span>
        <button onClick={siguientePais} disabled={countries.length <= 1}>{">"}</button>
      </div>

      {/* Navegación de ligas */}
      <div className="ligas-navegacion">
        <button onClick={anteriorLiga}>{"<"}</button>
        <span>{selectedLeague?.nombre}</span>
        <button onClick={siguienteLiga}>{">"}</button>
      </div>

      {/* Equipos */}
      <div className="equipos-grid">
        {selectedLeague?.teams
          ?.slice()
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((equipo) => (
            <div
              key={equipo.name}
              className="equipo-card"
              onClick={() => handleSeleccion(equipo)}
            >
              <img src={equipo.logo} alt={equipo.name} className="escudos" />
              <span className="text name">{equipo.name}</span>
              <span className="text media">{equipo.media}</span>
            </div>
          ))}
      </div>
    </div>
  );
};

export default SelectorEquipos;
